#ifndef CDOWNLOADER_CONFIG_H
#define CDOWNLOADER_CONFIG_H

#define DEFAULT_EXPANSION_DICTIONARY_FILE "@DEFAULT_EXPANSION_DICTIONARY_FILE@"

#cmakedefine DEBUG_METADATA_ACTIONS
#cmakedefine DEBUG_DOWNLOADING_ACTIONS
#cmakedefine DEBUG_ARCHIVE_EXTRACTING

#endif // CDOWNLOADER_CONFIG_H
